/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CapaPresentacion;

import CapaDatos.M_Cliente;
import CapaDatos.M_Compra;
import CapaDatos.M_Detalle;
import CapaDatos.M_Proveedor;
import CapaDatos.M_Usuario;
import CapaLogica.N_Cliente;
import CapaLogica.N_Compra;
import CapaLogica.N_Producto;
import CapaLogica.N_Proveedor;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author benja
 */
public class FrameIntCompra extends javax.swing.JInternalFrame {
    private List<M_Detalle> detalleProductos = new ArrayList<M_Detalle>();
    private M_Proveedor proveedor = new M_Proveedor();
    public M_Usuario current_usuario;
    /**
     * Creates new form FrameIntCompra
     */
    public FrameIntCompra() {
        initComponents();
    }

    void mostrarProductos(String buscar) {
        frmProducto.setVisible(true);
        frmProducto.setBounds(10, 10, 894, 400);
        try {
            DefaultTableModel modelo;
            N_Producto func = new N_Producto();
            modelo = func.buscar(buscar);
            tablalistadoProducto.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }
    void mostrarProveedores(String buscar) {
        frameProveedor.setVisible(true);
        frameProveedor.setBounds(10, 10, 728, 368);
        try {
            DefaultTableModel modelo;
            N_Proveedor func = new N_Proveedor();
            modelo = func.mostrar(buscar);
            tablaListadoAgregarProveedor.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }

    }

    void mostrarDetalleCompra() {
        DefaultTableModel modelo;
        String[] titulos = {"ID Producto", "Nombre Producto", "Precio", "Cantidad", "Total"};
        modelo = new DefaultTableModel(null, titulos);
        String[] registro = new String[5];
        detalleProductos.forEach(detalle -> {
            registro[0] = detalle.getIdproducto();
            registro[1] = "";
            registro[2] = String.valueOf(detalle.getPrecio());
            registro[3] = String.valueOf(detalle.getCantidad());
            registro[4] = String.valueOf(detalle.getTotal());
            modelo.addRow(registro);
        });

        tblListado.setModel(modelo);
    }

    void mostrarTotales(){
        DecimalFormat formato = new DecimalFormat("0.00");
        double subTotal = detalleProductos.stream().map(val->val.getTotal()).reduce(0.0,(a,b)->a+b);
        txtSubTotal.setText(formato.format(subTotal));
        txtIGV.setText(formato.format(subTotal*0.18));
        txtTotal.setText(formato.format(subTotal+(subTotal*0.18)));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmProducto = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablalistadoProducto = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtCantidadAgregarProducto = new javax.swing.JTextField();
        btnbuscarAgregarProducto = new javax.swing.JButton();
        btnSalirFrameProducto = new javax.swing.JButton();
        btnAgregarProductoSeleccionado = new javax.swing.JButton();
        txtbuscarProduco = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        frameProveedor = new javax.swing.JFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaListadoAgregarProveedor = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        txtBuscarProveedor = new javax.swing.JTextField();
        btnBuscarProveedor = new javax.swing.JButton();
        btnAgregarProveedor = new javax.swing.JButton();
        btnSalirAgregarProveedor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnProveedor = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cboTipoDocumento = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        txtIGV = new javax.swing.JTextField();
        btnSeleccionarProducto = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        btnVender = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListado = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        txtNumComprobante = new javax.swing.JTextField();
        dcfecha = new com.toedter.calendar.JDateChooser();

        tablalistadoProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Serie", "Nombre", "Fecha Ingreso", "Fecha Vencimiento", "P. Compra", "P. Venta", "Cantidad", "Categoria"
            }
        ));
        tablalistadoProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablalistadoProductoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablalistadoProducto);

        jLabel10.setText("Buscar por Nombre:");

        btnbuscarAgregarProducto.setText("Buscar");
        btnbuscarAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarAgregarProductoActionPerformed(evt);
            }
        });

        btnSalirFrameProducto.setText("Salir");
        btnSalirFrameProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirFrameProductoActionPerformed(evt);
            }
        });

        btnAgregarProductoSeleccionado.setText("Agregar");
        btnAgregarProductoSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoSeleccionadoActionPerformed(evt);
            }
        });

        jLabel20.setText("Cantidad:");

        javax.swing.GroupLayout frmProductoLayout = new javax.swing.GroupLayout(frmProducto.getContentPane());
        frmProducto.getContentPane().setLayout(frmProductoLayout);
        frmProductoLayout.setHorizontalGroup(
            frmProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmProductoLayout.createSequentialGroup()
                .addGroup(frmProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmProductoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbuscarProduco, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnbuscarAgregarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadAgregarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarProductoSeleccionado)
                        .addGap(121, 121, 121)
                        .addComponent(btnSalirFrameProducto))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmProductoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        frmProductoLayout.setVerticalGroup(
            frmProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmProductoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(frmProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(txtCantidadAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregarProductoSeleccionado))
                    .addGroup(frmProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtbuscarProduco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnbuscarAgregarProducto)
                        .addComponent(btnSalirFrameProducto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        tablaListadoAgregarProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaListadoAgregarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaListadoAgregarProveedorMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaListadoAgregarProveedor);

        jLabel21.setText("Buscar por Razon Social:");

        btnBuscarProveedor.setText("Buscar");
        btnBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProveedorActionPerformed(evt);
            }
        });

        btnAgregarProveedor.setText("Seleccionar");
        btnAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProveedorActionPerformed(evt);
            }
        });

        btnSalirAgregarProveedor.setText("Salir");
        btnSalirAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirAgregarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameProveedorLayout = new javax.swing.GroupLayout(frameProveedor.getContentPane());
        frameProveedor.getContentPane().setLayout(frameProveedorLayout);
        frameProveedorLayout.setHorizontalGroup(
            frameProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameProveedorLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btnBuscarProveedor)
                        .addGap(42, 42, 42)
                        .addComponent(btnAgregarProveedor)
                        .addGap(36, 36, 36)
                        .addComponent(btnSalirAgregarProveedor)
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        frameProveedorLayout.setVerticalGroup(
            frameProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProveedor)
                    .addComponent(btnAgregarProveedor)
                    .addComponent(btnSalirAgregarProveedor)
                    .addComponent(jLabel21))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setClosable(true);
        setResizable(true);

        jLabel4.setText("Estado");

        jLabel5.setText("Proveedor");

        txtSubTotal.setEditable(false);

        jLabel6.setText("Producto");

        btnProveedor.setText("Seleccionar");
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });

        jLabel7.setText("Sub Total");

        cboTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FACTURA", "BOLETA" }));
        cboTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoDocumentoActionPerformed(evt);
            }
        });

        jLabel8.setText("IGV");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CANCELADO", "ANULADO", "PENDIENTE" }));

        txtIGV.setEditable(false);

        btnSeleccionarProducto.setText("Agregar");
        btnSeleccionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarProductoActionPerformed(evt);
            }
        });

        jLabel9.setText("Total");

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        txtTotal.setEditable(false);

        btnVender.setText("Agregar");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        jLabel1.setText("N° Comprobante");

        tblListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Producto", "Nombre Producto", "Precio", "Cantidad", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListado);

        jLabel2.setText("Fecha");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo Comprobante");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dcfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(427, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(btnsalir)
                                    .addGap(91, 91, 91)
                                    .addComponent(btnActualizar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6))
                                            .addGap(27, 27, 27)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btnProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cboEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnSeleccionarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(109, 109, 109)
                                            .addComponent(btnEliminar)))))
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel9))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel8))))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNumComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dcfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(360, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5)
                                .addComponent(btnProveedor)
                                .addComponent(jLabel8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6)
                                .addComponent(btnSeleccionarProducto)
                                .addComponent(jLabel9)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnActualizar)
                        .addComponent(btnsalir)
                        .addComponent(btnEliminar)
                        .addComponent(btnVender))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        // TODO add your handling code here:
        mostrarProveedores("");
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void cboTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoDocumentoActionPerformed
        // TODO add your handling code here:
        
        //        generarNumeroComprobante();
    }//GEN-LAST:event_cboTipoDocumentoActionPerformed

    private void btnSeleccionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarProductoActionPerformed
        mostrarProductos("");
    }//GEN-LAST:event_btnSeleccionarProductoActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        if(detalleProductos.size()<1){
            JOptionPane.showMessageDialog(null,"Debe ingresar productos");
            return;
        }
        if(proveedor.getIdproveedor()==null){
            JOptionPane.showMessageDialog(null,"Debe seleccionar proveedor");
            return;
        }
        M_Compra compra = new M_Compra();
        compra.setFecha(dcfecha.getDate());
        compra.setNum_documento(txtNumComprobante.getText());
        compra.setTipo_documento(cboTipoDocumento.getSelectedItem().toString());
        compra.setSubtotal(Double.parseDouble(txtSubTotal.getText()));
        compra.setIgv(Double.parseDouble(txtIGV.getText()));
        compra.setTotal(Double.parseDouble(txtTotal.getText()));
        compra.setEstado(cboEstado.getSelectedItem().toString());
        compra.setIdusuario(current_usuario.getId());
        compra.setIdProveedor(proveedor.getRuc());
        compra.setDetalle(detalleProductos);

        new N_Compra().insertar(compra);
        JOptionPane.showMessageDialog(null, "Compra Ingresada");
        cboEstado.setSelectedIndex(0);
        cboTipoDocumento.setSelectedIndex(0);
        txtSubTotal.setText("");
        txtIGV.setText("");
        txtTotal.setText("");
        detalleProductos = new ArrayList<M_Detalle>();
        
        proveedor = new M_Proveedor();
        btnProveedor.setText("Seleccionar");
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        try {
            
            int cantidad = Integer.parseInt(tblListado.getModel().getValueAt(tblListado.getSelectedRow(), 3).toString());
            String idProducto = tblListado.getModel().getValueAt(tblListado.getSelectedRow(), 0).toString();
            
            detalleProductos = detalleProductos.stream().map(det->{
                if(det.getIdproducto().equals(idProducto)){
                    det.setCantidad(cantidad);
                    det.setTotal(cantidad*det.getPrecio());
                }
                return det;
            }).collect(Collectors.toList());
            
            mostrarDetalleCompra();
            mostrarTotales();
        } catch (NumberFormatException ex) {
            JOptionPane.showConfirmDialog(null, "Debe ingresar un valor numérico en Cantidad.");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String idProducto = tablalistadoProducto.getModel().getValueAt(tablalistadoProducto.getSelectedRow(), 0).toString();
        detalleProductos = detalleProductos.stream().filter(det -> !det.getIdproducto().equals(idProducto)).collect(Collectors.toList());
        mostrarTotales();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablalistadoProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablalistadoProductoMouseClicked
        //        M_Producto producto = new M_Producto();
        //        int fila=tablalistadoProducto.rowAtPoint(evt.getPoint());
        //        producto.setIdproducto(tablalistadoProducto.getValueAt(fila,0).toString());
        //        producto.setSerie(tablalistadoProducto.getValueAt(fila,1).toString());
        //        producto.setNombre(tablalistadoProducto.getValueAt(fila,2).toString());
        //        producto.setF_ingreso(java.sql.Date.valueOf(tablalistadoProducto.getValueAt(fila, 3).toString()));
        //        producto.setF_vencimiento(java.sql.Date.valueOf(tablalistadoProducto.getValueAt(fila, 4).toString()));
        //        producto.setP_compra(Double.parseDouble(tablalistadoProducto.getValueAt(fila,5).toString()));
        //        producto.setP_venta(Double.parseDouble(tablalistadoProducto.getValueAt(fila,6).toString()));
    }//GEN-LAST:event_tablalistadoProductoMouseClicked

    private void btnbuscarAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarAgregarProductoActionPerformed
        mostrarProductos(txtCantidadAgregarProducto.getText());
    }//GEN-LAST:event_btnbuscarAgregarProductoActionPerformed

    private void btnSalirFrameProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirFrameProductoActionPerformed
        txtCantidadAgregarProducto.setText("");
        frmProducto.setVisible(false);
    }//GEN-LAST:event_btnSalirFrameProductoActionPerformed

    private void btnAgregarProductoSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoSeleccionadoActionPerformed
        if (txtCantidadAgregarProducto.getText().equalsIgnoreCase("")) {
            JOptionPane.showConfirmDialog(null, "Debe ingresar una cantidad");
            return;
        }
               
        M_Detalle detalle = new M_Detalle();
        String idProducto = tablalistadoProducto.getModel().getValueAt(tablalistadoProducto.getSelectedRow(), 0).toString();

        if (!detalleProductos.stream().filter(det -> det.getIdproducto().equals(idProducto)).collect(Collectors.toList()).isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Producto Existe");
            frmProducto.setVisible(false);
            return;
        }
        double precio = Double.parseDouble(tablalistadoProducto.getModel().getValueAt(tablalistadoProducto.getSelectedRow(), 6).toString());
        int cantidad = Integer.parseInt(txtCantidadAgregarProducto.getText());

        detalle.setCantidad(cantidad);
        detalle.setIdproducto(idProducto);
        detalle.setPrecio(precio);
        detalle.setTotal(precio * cantidad);
        detalleProductos.add(detalle);
        mostrarDetalleCompra();
        mostrarTotales();
        frmProducto.setVisible(false);
    }//GEN-LAST:event_btnAgregarProductoSeleccionadoActionPerformed

    private void tablaListadoAgregarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListadoAgregarProveedorMouseClicked

    }//GEN-LAST:event_tablaListadoAgregarProveedorMouseClicked

    private void btnBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProveedorActionPerformed
        mostrarProveedores(txtBuscarProveedor.getText());
    }//GEN-LAST:event_btnBuscarProveedorActionPerformed

    private void btnAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProveedorActionPerformed
        // TODO add your handling code here:
        String idProveedor, razonSocial;

        idProveedor = tablaListadoAgregarProveedor.getModel().getValueAt(tablaListadoAgregarProveedor.getSelectedRow(), 0).toString();
        razonSocial= tablaListadoAgregarProveedor.getModel().getValueAt(tablaListadoAgregarProveedor.getSelectedRow(), 1).toString();
        proveedor.setIdproveedor(idProveedor);
        proveedor.setRazonsocial(razonSocial);
        btnProveedor.setText(razonSocial);
        frameProveedor.setVisible(false);
    }//GEN-LAST:event_btnAgregarProveedorActionPerformed

    private void btnSalirAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAgregarProveedorActionPerformed
        frameProveedor.setVisible(false);
    }//GEN-LAST:event_btnSalirAgregarProveedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregarProductoSeleccionado;
    private javax.swing.JButton btnAgregarProveedor;
    private javax.swing.JButton btnBuscarProveedor;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnSalirAgregarProveedor;
    private javax.swing.JButton btnSalirFrameProducto;
    private javax.swing.JButton btnSeleccionarProducto;
    private javax.swing.JButton btnVender;
    private javax.swing.JButton btnbuscarAgregarProducto;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JComboBox<String> cboTipoDocumento;
    private com.toedter.calendar.JDateChooser dcfecha;
    private javax.swing.JFrame frameProveedor;
    private javax.swing.JFrame frmProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tablaListadoAgregarProveedor;
    private javax.swing.JTable tablalistadoProducto;
    private javax.swing.JTable tblListado;
    private javax.swing.JTextField txtBuscarProveedor;
    private javax.swing.JTextField txtCantidadAgregarProducto;
    private javax.swing.JTextField txtIGV;
    private javax.swing.JTextField txtNumComprobante;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtbuscarProduco;
    // End of variables declaration//GEN-END:variables
}
